// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AImage: typeof import('ant-design-vue/es')['Image']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATable: typeof import('ant-design-vue/es')['Table']
    MePage: typeof import('./.vitepress/theme/components/MePage.tsx')['default']
    MyBooks: typeof import('./.vitepress/theme/components/MyBooks.tsx')['default']
    MyComponent: typeof import('./.vitepress/theme/components/MyComponent.tsx')['default']
    MyTag: typeof import('./.vitepress/theme/components/MyTag.tsx')['default']
    SimpleImg: typeof import('./.vitepress/theme/components/SimpleImg.tsx')['default']
    TagsOutlined: typeof import('@ant-design/icons-vue')['TagsOutlined']
    TestCom: typeof import('./.vitepress/theme/components/TestCom.tsx')['default']
  }
}
