// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AImage: typeof import('ant-design-vue/es')['Image']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    MePage: typeof import('./.vitepress/theme/components/MePage.tsx')['default']
    MyBooks: typeof import('./.vitepress/theme/components/MyBooks.tsx')['default']
    MyCodes: typeof import('./.vitepress/theme/components/MyCodes.tsx')['default']
    MyComponent: typeof import('./.vitepress/theme/components/MyComponent.tsx')['default']
    MyTag: typeof import('./.vitepress/theme/components/MyTag.tsx')['default']
    MyTimeLine: typeof import('./.vitepress/theme/components/MyTimeLine.tsx')['default']
    MyXmind: typeof import('./.vitepress/theme/components/MyXmind.tsx')['default']
    PageTags: typeof import('./.vitepress/theme/components/PageTags.tsx')['default']
    Phon: typeof import('./.vitepress/theme/components/Phon.tsx')['default']
    SimpleImg: typeof import('./.vitepress/theme/components/SimpleImg.tsx')['default']
    TestCom: typeof import('./.vitepress/theme/components/TestCom.tsx')['default']
    ToTop: typeof import('./.vitepress/theme/components/ToTop.tsx')['default']
  }
}
